### ISSUE TITLE
Cura 5.0 Support

### ISSUE THREAD

**Issue by lukasmwerner** [lwerner-lshigh/Dremel3D-CuraPrintr#6]
New goal!: 
* Time to get this working in Cura 5.0

**Comment by ghost** [comment]
Just as feedack: Cura 5.0.0, Ubuntu 22.04, Dremel 3D45.
This plugin seems to work fine (using the 5.0 branch).

The only feature that seems to not work yet is the "Monitor" tab. Cura says to "Connect the printer in order to monitor". 
A part from that, I successfully uploaded the code (via Ethernet) and the camera view is working.

**Comment by lukasmwerner** [comment]
Monitoring is a yet to be implemented feature.

**Comment by lukasmwerner** [comment]
For keeping this up to date with current statuses: I just submitted this for ultimaker's approval process so hopefully in the coming days the plugin will be added to the store.

**Comment by lukasmwerner** [comment]
Closed as this is now on the store
